### ISSUE TITLE
[SETTING] 백엔드 프로젝트 초기 설정

### ISSUE THREAD

**Issue by rigizer** [E-CO-CO/Ecoco-Server#2]
## 🌎 이슈 요약
백엔드 프로젝트 초기 설정

<br/><br/>

## ✅ To-Do
- [ ] application.properties -> application.yml 변경
- [ ] 포트번호 설정
- [ ] swagger config 추가
- [ ] 데이터베이스 정보 추가
- [ ] JPA Entity, Repository 추가
- [ ] QueryDSL QClass, Repository 추가
- [ ] BaseResponse 구현
- [ ] ErrorResponse 구현
- [ ] GlobalExceptionHandler 구현
